import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const d2coding = localFont({
  src: [
    {
      path: '../public/fonts/d2coding.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/d2coding-bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-d2coding',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${d2coding.variable}`}>
      <body>{children}</body>
    </html>
  );
}
