import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import ToggleDark from '@/components/common/toggle-dark';
import { ThemeProvider } from 'next-themes';

const d2coding = localFont({
  src: [
    {
      path: '../public/fonts/d2coding.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/d2coding-bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-d2coding',
  display: 'swap',
});

export const metadata: Metadata = {
  title: {
    template: '%s | Yoyang',
    default: '홈 | Yoyang',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${d2coding.variable} relative min-h-screen min-w-screen`}
      >
        <ThemeProvider storageKey="dark" attribute="class" enableSystem>
          {children}
          <ToggleDark />
        </ThemeProvider>
      </body>
    </html>
  );
}
